name: Build and Deploy .NET Application

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build application
      run: dotnet build --configuration Release --no-restore

    - name: Publish application
      run: dotnet publish --configuration Release --output ./published --no-restore

    - name: Deploy to server (Simulacion)
      run: |
        echo "Simulando la transferencia de archivos al servidor..."
        echo "Despliegue ejecutado de manera exitosa"
